#!/bin/bash

printf "NORMAL    $RED RED $YELLOW YELLOW $GREEN GREEN $BLUE BLUE $CYAN CYAN $MAGENTA MAGENTA $WHITE WHITE $GRAY GRAY $BLACK BLACK $RESET\n"
printf "BOLD      $BOLD$RED RED $YELLOW YELLOW $GREEN GREEN $BLUE BLUE $CYAN CYAN $MAGENTA MAGENTA $WHITE WHITE $GRAY GRAY $BLACK BLACK $RESET\n"
printf "DIM       $DIM$RED RED $YELLOW YELLOW $GREEN GREEN $BLUE BLUE $CYAN CYAN $MAGENTA MAGENTA $WHITE WHITE $GRAY GRAY $BLACK BLACK $RESET\n"
printf "UNDERLINE $UNDERLINE$RED RED $YELLOW YELLOW $GREEN GREEN $BLUE BLUE $CYAN CYAN $MAGENTA MAGENTA $WHITE WHITE $GRAY GRAY $BLACK BLACK $RESET\n"
printf "BLINK     $BLINK$RED RED $YELLOW YELLOW $GREEN GREEN $BLUE BLUE $CYAN CYAN $MAGENTA MAGENTA $WHITE WHITE $GRAY GRAY $BLACK BLACK $RESET\n"
printf "INVERTED  $INVERTED$RED RED $YELLOW YELLOW $GREEN GREEN $BLUE BLUE $CYAN CYAN $MAGENTA MAGENTA $WHITE WHITE $GRAY GRAY $BLACK BLACK $RESET\n"
printf "HIDDEN    $HIDDEN$RED RED $YELLOW YELLOW $GREEN GREEN $BLUE BLUE $CYAN CYAN $MAGENTA MAGENTA $WHITE WHITE $GRAY GRAY $BLACK BLACK $RESET\n"

printf "BG        $BG_RED BG_RED $BG_YELLOW BG_YELLOW $BG_GREEN BG_GREEN $BG_BLUE BG_BLUE $BG_CYAN BG_CYAN $BG_MAGENTA BG_MAGENTA $BG_WHITE BG_WHITE $BG_GRAY BG_GRAY $BG_BLACK BG_BLACK $RESET$BG_DEFAULT\n"
printf "BG        $BG_LIGHT_RED BG_LIGHT_RED $BG_LIGHT_YELLOW BG_LIGHT_YELLOW $BG_LIGHT_GREEN BG_LIGHT_GREEN $BG_LIGHT_BLUE BG_LIGHT_BLUE $BG_LIGHT_CYAN BG_LIGHT_CYAN $BG_LIGHT_MAGENTA BG_LIGHT_MAGENTA $BG_LIGHT_GRAY BG_LIGHT_GRAY $RESET$BG_DEFAULT\n"

printf "LIGHT     $LIGHT_RED LIGHT_RED $LIGHT_YELLOW LIGHT_YELLOW $LIGHT_GREEN LIGHT_GREEN $LIGHT_BLUE LIGHT_BLUE $LIGHT_CYAN LIGHT_CYAN $LIGHT_MAGENTA LIGHT_MAGENTA $RESET \n"